- hosts: 10.0.0.211
  tasks:
    - name: Install PowerShell modules
      win_psmodule:
        name: '{{ item }}'
        state: present
      with_items:
        - xActiveDirectory
        - xComputerManagement
        - xNetworking
        - xDnsServer
        - xActiveDirectory

    - name: Set WinRM service to automatic
      win_dsc:
        resource_name: Service
        Name: WinRM
        StartupType: Automatic

    - name: Set hostname
      win_dsc: 
        resource_name: xComputer
        name: '{{ hostname }}'
      register: SetHostname

    - name: Reboot 1
      win_reboot:
      when: SetHostname.reboot_required == True

    - name: Set DNS server address
      win_dsc:
        resource_name: xDnsServerAddress
        AddressFamily: IPV4
        InterfaceAlias: '{{ interface_alias }}'
        Address: 127.0.0.1

    - name: Install Windows Features
      win_feature:
        name: AD-Domain-Services,DNS
        state: present

    - name: Promote to domain controller
      win_dsc:
        resource_name: xADDomain
        DomainName: '{{ domain_name }}'
        SafemodeAdministratorPassword: '{{ safe_mode_password }}'
        DomainAdministratorCredential_username: '{{ DomainAdministratorCredential_username }}'
        DomainAdministratorCredential_password: '{{ DomainAdministratorCredential_password }}'
      register: PromoteToDomainController

    - name: Reboot 2
      win_reboot:
      when: PromoteToDomainController.reboot_required == True

    - name: Set DNS forwarders
      win_dsc:
        resource_name: xDnsServerForwarder
        IsSingleInstance: Yes 
        IPAddress: '{{ dns_forwarder_address }}'