- hosts: 10.0.0.250
  tasks:
    - name: 
      win_psmodule:
        name: '{{ item }}'
        state: present
      with_items:
        - xActiveDirectory
        - xComputerManagement
        - xNetworking

    - name: Set hostname
      win_dsc: 
        resource_name: xComputer
        name: adatdc01

    - name: Set DNS server address
      win_dsc:
        resource_name: xDnsServerAddress
        AddressFamily: IPV4
        InterfaceAlias: Chicago
        Address: 127.0.0.1
