- hosts: litcli01.litware.com
  tasks:
    - name: InstallChocolatey
      win_psmodule:
        name: cChoco
        state: present
    
    - name: InstallChoco
      win_dsc:
        resource_name: cChocoInstaller
        InstallDir: "C:\\Choco"
    
    - name: InstallGoogleChrome
      win_dsc:
        resource_name: cChocoPackageInstaller
        name: googlechrome
        ensure: present

    - name: InstallApplications
      win_chocolatey:
        name: '{{ item }}'
        ensure: present
      with_items: 
        - notepadplusplus.install
        - putty.install
